---

default_homebrew_taps:
  - name: homebrew/cask-fonts
  - name: homebrew/services
  - name: ngrok/ngrok

default_homebrew_packages:
  - awscli
  - coreutils
  - dockutil # configures mac dock
  - ghostscript
  - helm
  - icu4c
  - imagemagick
  - jpeg
  - kubernetes-cli # kubectl
  - libpq # for pg gem
  - libsodium
  - libtiff
  - memcached
  - minikube # Local K8S cluster creation
  - ngrok
  - openjdk
  - openssl
  - readline
  - sqlite3
  - tcl-tk
  - watch
  - xz
  - zlib

default_applications:
  - app_name: ChatGPT
    app_url: https://persistent.oaistatic.com/sidekick/public/ChatGPT_Desktop_public_latest.dmg
    download_file_type: dmg
    installer_type: app
    install_method: dmg

  - app_name: Docker
    app_url: https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=module
    download_file_type: dmg
    installer_type: app
    install_method: dmg

  - app_name: Google Chrome
    app_url: https://dl.google.com/chrome/mac/stable/CHFA/googlechrome.dmg
    download_file_type: dmg
    installer_type: app
    install_method: dmg

  - app_name: iTerm
    app_url: https://iterm2.com/downloads/stable/latest
    download_file_type: zip
    installer_type: app
    install_method: dmg

  - app_name: Postman
    app_url: https://dl.pstmn.io/download/latest/osx
    download_file_type: zip
    installer_type: app
    install_method: dmg

  - app_name: Slack
    app_url: https://slack.com/ssb/download-osx
    download_file_type: dmg
    installer_type: app
    install_method: dmg

  - app_name: Visual Studio Code
    app_url: https://go.microsoft.com/fwlink/?LinkID=620882
    download_file_type: zip
    installer_type: app
    install_method: dmg

  - app_name: zoom.us
    app_url: https://zoom.us/client/6.0.2.33403/zoomusInstallerFull.pkg?archType=arm64 # AppleSilicon mirror
    download_file_type: pkg
    installer_type: dmg
    install_method: dmg

desired_dock_apps:
  - "Postman.app"
  - "System Settings.app"
  - "Slack.app"
  - "Visual Studio Code.app"
  - "zoom.us.app"
